### ISSUE TITLE
read-from/write-to fifos not implemented in Windows

### ISSUE THREAD

**Issue by tavmem** [kevinlawler/kona#345]
This issue is related to issue #110 (IO to /dev/fd/* or fifos).

First, /dev/fd/* does not exist in Windows, so that part is not relevant.

Second, "fifos" as such don't exist either.  For example, you can't do "mkfifo".
The counterpart in Windows is "named pipes".
IPC was implemented in Windows using sockets, but "named pipes" was not yet implemented.

Not clear whether "named pipes" was implemented for Windows in k2.8 or k3.2.
However, for now, I will assume that it was.

**Comment by tavmem** [comment]
Although a FIFO (in Linux/Unix) is similar to a named pipe (in Windows) there are several differences.  Four of the differences are:
-  Linux/Unix FIFOs might be half duplex.  BSD supports read and write simultaneously. In Linux you can open a FIFO for read and write.  POSIX leaves this behavior undefined.  In Windows, named pipes are bidirectional
-  In Linux/Unix a FIFO is limited to a single machine. In Windows named pipes work accross networked machines.
-  Linux/Unix FIFOs are byte oriented.  In Windows named pipes are message oriented.
-  In Linux/Unix you can create the FIFO with the shell (using "mkfifo" or "mknode") or from a program using system calls (mkfifo() or mknode()).  In Windows the named pipe is created by a server program using the function "CreateNamedPipe().  There is no command line interface in Windows for creating a named pipe.

**Comment by bakul** [comment]
My point of mentioning named pipes was not to do anything
special for them but to indicate that at least in Unix the
same design should work for them unchanged if kona handles
/dev/fd/<number>, /dev/stdin, /dev/stdout right -- it should
just accept what the OS provides and not do anything heroic.
I believe Windows named pipes can also be byte oriented but
don't really know since I don't use Windows. As a general
guideline portability should trump supporting all the bells
and whistles on any specific platform. You will still have
platform specific code but hopefully it is minimized and
limited to one or two files.

**Comment by tavmem** [comment]
Good point!
In Linux/Unix /dev/fd/\<number\>, /dev/stdin, /dev/stdout are all files which do not exist in Windows.
In Linux/Unix a FIFO is a type of file.  This type of file does not exist in Windows.

A named pipe in Windows is simply an alternate means of IPC (instead of sockets).
Since we can do IPC in Windows (with sockets), there is probably no need to use named pipes to create an alternate IPC functionality in Windows.

Unless there is something we have missed, it looks like we can close this issue.

**Comment by bakul** [comment]
On Mon, 15 Jun 2015 12:06:51 PDT Tom Szczesny <notifications@github.com> wrote:
> 
> Unless there is something we have missed, it looks like we can close this
> issue.

I think so. Many thanks!
