### ISSUE TITLE
Another crash with likely illegal syntax

### ISSUE THREAD

**Issue by gitonthescene** [kevinlawler/kona#614]
This also crashes the second time, making it seem like it's leaving the interpreter in a bad state.

```
kona      \ for help. \\ to exit.

  ($:)/1234
()
  ($:)/1234
[1]    62632 segmentation fault  ./k
```

**Comment by tavmem** [comment]
In k2.8:
```
K 2.8 2000-10-10 Copyright (C) 1993-2000 Kx Systems
\ for help. \\ to exit.

  ($:)/1234
"1234"
  ($:)/1234
"1234"
```

**Comment by tavmem** [comment]
```($:)/1234``` began to yield a segfault in kona after the 3rd commit made on Oct 20, 2015  945ef59af718cfe34c70e05a5477094403630992
This commit was made to address an apparent bug in k2.8 which was fixed by k3.2.
See issue #380.

In k2.8, when executing the "over/monad" case ```f:{(x+1)!3}; f/2```, k2.8 loops endlessly until you hit Ctl-c.
In k3.2, ```f:{(x+1)!3}; f/2``` yields 1

Before the 3rd commit of Oct 20,2015 945ef59af718cfe34c70e05a5477094403630992 kona also looped endlessly.
After the commit, kona yields 1.
However, this commit created the segfault condition on ```($:)/1234```
